development:
  secret_key_base: __RAILS_SECRET
  stripe_publishable_key: __STRIPE_PUBLISHABLE
  stripe_secret_key: __STRIPE_SECRET
  stripe_client_id: __STRIPE_CLIENT
  fee_percentage: 10

test:
  secret_key_base: __RAILS_SECRET
